@startuml
'https://plantuml.com/sequence-diagram

title 关键行为（Pay,Event,Bidding,Arpu）流程图
autonumber

==发起激活==
投放人员 -> 广告平台 : 设置投放点击监测链接
广告平台 -> APP客户端: 下载APP
广告平台 -> angogo回传服务: 透传点击记录
APP客户端 -> angogo回传服务: 打开APP，激活上报
angogo回传服务 ->angogo回传服务: 匹配点击记录
note right
以点击记录中渠道号投放配置为准（第3步），
匹配激活回传模型（注：没点击记录不回传）
end note
angogo回传服务 --> 广告平台: 激活上报回传
angogo回传服务 ->angogo回传服务: 保存激活记录
angogo回传服务 ->BigData平台: 发送激活数据（队列）

/'newpage'/
==发起Pay付费行为==

APP客户端 -> angogo产品后台: App发起付费(略)
angogo产品后台 --> angogo回传服务: 付费队列
note left
设备信息、金额/分、订单号
end note
angogo回传服务 ->angogo回传服务: 匹配激活记录（第7步）
note left
根据设备信息匹配激活记录，
(注：7天内，没激活记录不回传)
激活记录的渠道号配置金额匹配
end note
angogo回传服务-->广告平台: 付费回传
angogo回传服务->angogo回传服务:保存付费记录

==发起Event行为组合==
BigData平台->BigData平台:kafka订阅神策事件
BigData平台-->angogo回传服务:Event队列（报文来源第8步）
angogo回传服务->angogo回传服务:匹配Event模型
note left
报文中channel投放配置
event=事件ID:事件名:属性值，
事件组合匹配
end note
angogo回传服务-->广告平台: 关键行为回传
angogo回传服务->angogo回传服务:保存Event记录

==发起Bidding结算价格==
BigData平台->BigData平台:Bidding脚本
BigData平台-->angogo回传服务:Bidding队列
angogo回传服务->angogo回传服务:匹配Bidding模型
note left
报文中channel投放配置,
bidding价格匹配
end note
angogo回传服务-->广告平台: 关键行为回传
angogo回传服务->angogo回传服务:保存Bidding记录

==发起ARPU用户平均收入==
BigData平台->BigData平台:ARPU脚本
BigData平台-->angogo回传服务:Arpu队列
angogo回传服务->angogo回传服务:匹配ARPU模型
note left
报文中channel投放配置,
ARPU阈值匹配
end note
angogo回传服务-->广告平台: 关键行为回传
angogo回传服务->angogo回传服务:保存ARPU记录

@enduml