@startuml
'https://plantuml.com/sequence-diagram
title 市二院药房对接创业流程图
autonumber

==1.1药房发起请领==
坐标iHO -> 坐标iHO: 药房入库：生成请领单
坐标iHO -> 坐标集成平台: 药房请领单审核
note right
1.药库出库->药房请领，可看到请领单
2.埋点触发，接口编码:iho_drugs_requestAudit
end note
坐标集成平台 -> 坐标集成平台: 组装接口格式
坐标集成平台 -> 创业药库: 生成请领单（创业定义）
坐标集成平台 <-- 创业药库: return 结果
坐标iHO <-- 坐标集成平台: return 结果

==1.2创业请领单审核通知==
创业药库 -> 坐标集成平台: 请领单审核通知
note right
注：请领单单据billid,
药品信息，数量，批次号batchno
end note
坐标iHO <- 坐标集成平台: 调用请领单通知接口
坐标iHO --> 坐标iHO: 药库入库流程
note right
1.生成药库调入单
2.自动生成已审核的药库出库单
如果需要药房审核确认则3，不需要则4
3.生成待审核的药库出库单，药房入库单
4.生成已审核的药库出库单，药房入库单
end note

==2.1药房发起退库单==
坐标iHO -> 坐标集成平台: 埋点触发:药房退库
note right
埋点触发，接口编码:iho_drugs_returnOutboundListExamine
end note
坐标集成平台 -> 坐标集成平台: 组装接口格式
创业药库 <- 坐标集成平台: 调用药房退库单(创业定义)
创业药库 --> 坐标集成平台: return 结果
坐标iHO <-- 坐标集成平台: return 结果

==2.2创业退库单通知==
创业药库 -> 坐标集成平台: 退库单审核通知
note right
注：退库单据billid,
药品信息，数量，批次号batchno
end note
坐标iHO <- 坐标集成平台: 调用退库单通知接口
坐标iHO -> 坐标iHO: 更新退库单状态
note right
注：退库药品信息，数量，批次号batchno
end note
@enduml