@startuml
'https://plantuml.com/sequence-diagram
title 静配中心
autonumber

==1.医嘱发送流程图==
医生站 -> 护士站: 发送医嘱
护士站 -> 收费: 校对发送，费用记帐
收费 -> 药房: Mq推送发药数据
药房 -> 药房: 1判断执行科室不包含静配，执行发药(略)
药房 -> 静配中心: 2判断执行科室包含静配，推送到静配中心
==2.静脉配液流程==
静配中心 -> 合理用药: 医嘱审查：人工/自动触发审方（异步）
静配中心 <-- 合理用药: 返回审查结果：如配伍禁忌
医生站 <-- 静配中心: 医嘱审查：1.退单申请
静配中心 --> 静配中心: 医嘱审查：2.0接收
静配中心 --> 静配中心: 2.1分配批次：医嘱拆分，匹配批次规则
静配中心 --> 静配中心: 2.2瓶签打印：打签
静配中心 --> 静配中心: 2.3药品配液：配液
静配中心 --> 静配中心: 2.4成品复核：复核
静配中心 --> 静配中心: 2.4成品装箱：装箱
静配中心 --> 静配中心: 2.5成品交接：交接
==3.静配发药收费流程==
静配中心 --> 药房: 自动执行发药，费用记帐
药房 --> 药房: 执行发药流程（略）



@enduml